---
# Create new Networks / delete unused Networks
### create bridged WAN network
- community.libvirt.virt_net:
    command: define
    name: wan01
    xml: templates/if_wan01.xml.j2
    state: active
    autostart: yes
# create isolated LAN network
- community.libvirt.virt_net:
    command: define
    name: lan01
    xml: templates/if_lan01.xml.j2
    state: active
    autostart: yes
# destory default network
- community.libvirt.virt_net:
    command: destroy
    name: default
### adjust iptables
#- name: j2 iptables template deploy
#  template:
#    src: templates/iptables.j2
#    dest: /etc/sysconfig/iptables
